

GRANT R_USER to BORODKO ;
GRANT R_USER to AKSENOVA ;
GRANT R_USER to BLINKOVSKYI;
GRANT R_USER to KOVALEV ;
GRANT R_USER to KOZINJUK ;
GRANT R_USER to PISKUN ;
GRANT R_USER to PITLIAKE;
GRANT R_USER to VOLKODATOV ;
-- S_DEPARTAMENT
INSERT INTO S_DEPARTMENT (ID_DEP, DEP_NAME_SHORT, DEP_NAME_LONG) VALUES (2, 'Лаборатория №1', 'Лаборатория №1');
-- S_APPROVED
INSERT INTO S_APPROVED (ID_APR, ID_DEP, APR_ITEM_OK, APR_ITEM_FAILED, APR_REPORT_OK, APR_REPORT_FAILED)  VALUES (2, 2, 'Соотв.', 'Не соотв.', 'Соответствует', 'Не соответствует');
-- S_JOB
INSERT INTO S_JOB (ID_JOB, JOB_NAME_SHORT, JOB_NAME_LONG) VALUES (2, 'Инженер', 'Инженер');
--
INSERT INTO SYS_USERS (ID_USER, ID_DEP, ID_JOB, USER_LOGIN, USER_ROLE, USER_FAM, USER_IMA, USER_OTH) VALUES (3, 2, 2, 'BORODKO', 'R_USER', 'Бородько', 'Максим', 'Васильевич');
INSERT INTO SYS_USERS (ID_USER, ID_DEP, ID_JOB, USER_LOGIN, USER_ROLE, USER_FAM, USER_IMA, USER_OTH) VALUES (4, 2, 2, 'AKSENOVA', 'R_USER', 'Аксенова', 'Зинаида', 'Давидовна');
INSERT INTO SYS_USERS (ID_USER, ID_DEP, ID_JOB, USER_LOGIN, USER_ROLE, USER_FAM, USER_IMA, USER_OTH) VALUES (5, 2, 2, 'BLINKOVSKYI', 'R_USER', 'Блинковский', 'Иван', 'Николаевич');
INSERT INTO SYS_USERS (ID_USER, ID_DEP, ID_JOB, USER_LOGIN, USER_ROLE, USER_FAM, USER_IMA, USER_OTH) VALUES (6, 2, 2, 'KOVALEV', 'R_USER', 'Ковалев', 'Александр', 'Васильевич');
INSERT INTO SYS_USERS (ID_USER, ID_DEP, ID_JOB, USER_LOGIN, USER_ROLE, USER_FAM, USER_IMA, USER_OTH) VALUES (7, 2, 2, 'KOZINJUK', 'R_USER', 'Козынюк', 'Михаил', 'Викторович');
INSERT INTO SYS_USERS (ID_USER, ID_DEP, ID_JOB, USER_LOGIN, USER_ROLE, USER_FAM, USER_IMA, USER_OTH) VALUES (8, 2, 2, 'PISKUN', 'R_USER', 'Пискун', 'Денис', 'Батькович');
INSERT INTO SYS_USERS (ID_USER, ID_DEP, ID_JOB, USER_LOGIN, USER_ROLE, USER_FAM, USER_IMA, USER_OTH) VALUES (9, 2, 2, 'PITLIAKE', 'R_USER', 'Пытляк', 'Евгений', 'Батькович');
INSERT INTO SYS_USERS (ID_USER, ID_DEP, ID_JOB, USER_LOGIN, USER_ROLE, USER_FAM, USER_IMA, USER_OTH) VALUES (10, 2, 2, 'VOLKODATOV', 'R_USER', 'Волкодатов', 'Александр', 'Андреевич');

-- привязка профилей
INSERT INTO I_USER_PRF (ID_USERPRF, ID_USER, ID_PRF) VALUES (3, 3, 99);
INSERT INTO I_USER_PRF (ID_USERPRF, ID_USER, ID_PRF) VALUES (4, 4, 99);
INSERT INTO I_USER_PRF (ID_USERPRF, ID_USER, ID_PRF) VALUES (5, 5, 99);
INSERT INTO I_USER_PRF (ID_USERPRF, ID_USER, ID_PRF) VALUES (6, 6, 99);
INSERT INTO I_USER_PRF (ID_USERPRF, ID_USER, ID_PRF) VALUES (7, 7, 99);
INSERT INTO I_USER_PRF (ID_USERPRF, ID_USER, ID_PRF) VALUES (8, 8, 99);
INSERT INTO I_USER_PRF (ID_USERPRF, ID_USER, ID_PRF) VALUES (9, 9, 99);
INSERT INTO I_USER_PRF (ID_USERPRF, ID_USER, ID_PRF) VALUES (10, 10, 99);


COMMIT;


